function anwser(){
    if(document.getElementById("vastaus1").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeHirvi.Joni.html")
    }
    if(document.getElementById("vastaus2").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeIlves.Joni.html")
    }
    if(document.getElementById("vastaus3").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeTiikeri.Joni.html")
    }
    if(document.getElementById("vastaus4").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeHuuhkaja.Joni.html")
    }
    if(document.getElementById("vastaus5").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeKettu.Joni.html")
    }
};
function anwser2(){
    if(document.getElementById("vastaus6").checked){
        window.location.replace("../../Luonnontiede/Kysymys2/infoSivut2/LuonnontiedeHiili.html")
    }
    if(document.getElementById("vastaus7").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeIlves.Joni.html")
    }
    if(document.getElementById("vastaus8").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeTiikeri.Joni.html")
    }
    if(document.getElementById("vastaus9").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeHuuhkaja.Joni.html")
    }
    if(document.getElementById("vastaus10").checked){
        window.location.replace("../../Luonnontiede/Kysymys1/infoSivut/LuonnontiedeKettu.Joni.html")
    }
};